# Canva API Configuration
# This file stores configuration settings for the Canva API client.

# The client ID for your Canva API app.
# It can also be set using the CANVA_CLIENT_ID environment variable.
client_id: ""

# The client secret for your Canva API app.
# It can also be set using the CANVA_CLIENT_SECRET environment variable.
client_secret: ""

# The brand template ID to be used for generating images.
# It can also be set using the CANVA_BRAND_TEMPLATE_ID environment variable.
brand_template_id: ""
