# Configuration for image generation
# Unified configuration for both dall-e-3 and other image models.
# The 'style' and 'quality' parameters are only used if the model is 'dall-e-3'.
model: "dall-e-3"
style: "vivid"
quality: "hd"
